folio-org/edge-common-spring

.editorconfig, CONTRIBUTING.md, NEWS.md, PERSONAL_DATA_DISCLOSURE.md, PULL_REQUEST_TEMPLATE.md, README.md, pom.xml, src/test/resources/application.yml
**Purpose**
https://issues.folio.org/browse/EDGCMNSPR-1
**Approach**
Created base module skeleton with files, regarding this manual: https://dev.folio.org/guidelines/create-new-repo/
=> EDGCMNSPR-1 Initial commit

README.md, src/main/java/org/folio/edgecommonspring/filter/EdgeSecurityFilter.java, src/test/java/org/folio/edgecommonspring/filter/EdgeSecurityFilterTest.java
https://issues.folio.org/browse/EDGCMNSPR-3
Currently, any module that uses edge-common-spring will fail to open swagger docs because swagger endpoints are not listed as excluded if EdgeSecurityFilter.
Added swagger endpoints to the list of excluded in EdgeSecurityFilter by default.
Unit tests are updated.
Ideally all of the PRs involved in breaking …
=> EDGCMNSPR-3 Add swagger endpoints to the list of excluded

NEWS.md, pom.xml
[EDGCMNSPR-4](https://issues.folio.org/browse/EDGCMNSPR-4) - Release 1.0.0
=> EDGCMNSPR-4 - Release 1.0.0

src/main/resources/log4j2.properties
https://issues.folio.org/browse/EDGCMNSPR-5
=> EDGCMNSPR-5 Add log.level variable as system property

src/main/java/org/folio/edgecommonspring/filter/EdgeSecurityFilter.java
https://issues.folio.org/browse/EDGCMNSPR-7
Added return to the method when an exception was thrown
=> EDGCMNSPR-7 Stop filter chain if authorization exception was thrown

NEWS.md, pom.xml
https://issues.folio.org/projects/EDGCMNSPR/issues/EDGCMNSPR-8?filter=allissues
- updated NEWS
- updated pom with new version for new development iteration
- changed edge-api-utils version to latest release
=> Release 1.1.0

pom.xml
Fix log4j2 RCE vulnerability
log4j2 version set to 2.17.0
=> upgrade log4j version

pom.xml
[EDGCMNSPR-9](https://issues.folio.org/browse/EDGCMNSPR-9) - edge-common-spring: folio-spring-base v2 update
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> EDGCMNSPR-9 - edge-common-spring: folio-spring-base v2 update

pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
=> EDGCMNSPR-9 - folio spring base v.3.0.1

.gitignore, pom.xml
* Update folio-spring-base to v4.1.0
* Add gitignore
* remove duplicate plugin
=> EDGCMNSPR-11 Update folio-spring-base to v4.1.0

NEWS.md, pom.xml
[EDGCMNSPR-20](https://issues.folio.org/browse/EDGCMNSPR-20) - Release 2.0.1
=> EDGCMNSPR-20 - Release 2.0.1

NEWS.md, pom.xml
[EDGCMNSPR-23](https://issues.folio.org/browse/EDGCMNSPR-23) - EDGCMNSPR (edge-common-spring) MG Bugfix Release - 2.0.2
=> EDGCMNSPR-23 - Release 2.0.2

pom.xml
[EDGCMNSPR-26](https://issues.folio.org/browse/EDGCMNSPR-26) - edge-common-spring: spring upgrade
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> EDGCMNSPR-26 - upgrade folio-spring-base to 5.0.0

NEWS.md, pom.xml
[EDGCMNSPR-27](https://issues.folio.org/browse/EDGCMNSPR-27) - edge-common-spring: Nolana release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> EDGCMNSPR-27 - Release 2.1.0

NEWS.md, pom.xml
[EDGCMNSPR-32](https://issues.folio.org/browse/EDGCMNSPR-32) - edge-common-spring: module release
=> Release 2.2.0

pom.xml
The purpose of the PR is to update folio spring base version to 7.0.0
**Evidence:**
After changing the version, build is successful.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
=> EDGCMNSPR-35 folio-spring-base version updated to 7.0.0

src/main/java/org/folio/edgecommonspring/security/SecurityManagerService.java, src/test/java/org/folio/edgecommonspring/security/SecurityManagerServiceTest.java
The cached system user is returned when is has been expired for up to 30 seconds.
Cause: SecurityManagerService.java uses Instant.now().minusSeconds(30L), it should use Instant.now().plusSeconds(30L).
Also, add unit tests for this.
**_Reference ticket : https://issues.folio.org/browse/FOLSPRINGB-120_**
In edge-common-spring when we retrieve the token from the cache, we first check to see if it is expired. However, the request will take some unknown amount of time. It would be rare but possible that the token could expire during the time after which it was retrieved and used in the actual request. Adding a buffer should be sufficient to solve this.
Before merging this PR, please go through the following list and take appropriate action.
- Does this PR meet or exceed the expected quality …
=> EDGCMNSPR-39 : Implement Expired system user token from cache

pom.xml
Upgrade folio-spring dependencies in pom version.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.
While it's helpful for reviewers to help …
=> EDGCMNSPR-40 Upgrade the dependency version of folio spring library

NEWS.md, pom.xml
[EDGCMNSPR-41](https://issues.folio.org/browse/EDGCMNSPR-41) - edge-common-spring: module release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> EDGCMNSPR-41 - Release 2.3.0

NEWS.md, pom.xml
[EDGCMNSPR-44](https://issues.folio.org/browse/EDGCMNSPR-44) - edge-common-spring: module release
Release v2.3.1.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> Release 2.3.1

NEWS.md, pom.xml
[EDGCMNSPR-44](https://issues.folio.org/browse/EDGCMNSPR-44) - edge-common-spring: module release
Release v2.3.2.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> Release 2.3.2

NEWS.md, pom.xml, src/main/java/org/folio/edgecommonspring/client/EnrichUrlClient.java
=> Release 2.4.3

pom.xml
Dependency updated to release version
=> Dependency updated to release version

NEWS.md, pom.xml
[EDGCMNSPR-55](https://folio-org.atlassian.net/browse/EDGCMNSPR-55) - Release 2.4.5
=> EDGCMNSPR-55 - Release 2.4.5

pom.xml, src/main/java/org/folio/edgecommonspring/config/FeignClientConfiguration.java
Bump up applications-poc-tools dependencies to 1.5.6 to support Hostname Verification for TLS connections
=> Bump up applications-poc-tools dependencies to 1.5.6

NEWS.md, pom.xml
[EDGCMNSPR-56](https://folio-org.atlassian.net/browse/EDGCMNSPR-56) - Release 2.4.6
=> EDGCMNSPR-56 - Release 2.4.6

Jenkinsfile, pom.xml, src/main/java/org/folio/edgecommonspring/config/ConditionalEdgeCommonConfiguration.java, src/main/java/org/folio/edgecommonspring/config/EdgeCommonSpringComponentScanConfiguration.java, src/main/java/org/folio/edgecommonspring/config/FeignClientConfiguration.java, src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
This PR bumps the parent POM to v3.4.3 and folio-spring version to v9.0.0, to make it compatible with Java 21. It also restructures the feign config class, to break up the `@ConditionalOnMissingBean` and `@ComponentScan` annotation, as these are no longer allowed by Spring to both be on a single class.
This PR also bumps the project to Java 21 and bumps the major version, so this is now 3.0.0-SNAPSHOT
https://folio-org.atlassian.net/browse/EDGCMNSPR-59
This change is important, as the previous approach to the Feign client configuration is not compatible with the latest version of Spring Framework, which we need in order to upgrade edge modules to Java 21+. The latest Spring Framework specifically disallows combining `@ConditionalOnMissingBean` and `@ComponentScan` annotations on the same …
=> EDGCMNSPR-59 Bump to Java 21
